<a href="https://colab.research.google.com/github/StevenDavid04/Colab/blob/main/StevenDavidLab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [3]:
for i in range(5,8):
    print(i)

5
6
7


In [4]:
for i in range(3):
    print("Test Number: ",i)

Test Number:  0
Test Number:  1
Test Number:  2


#Function

In [5]:
def square(x):
    return x**2

In [6]:
square(5)

25

In [7]:
def add_two(x):
    return x+2

In [8]:
add_two(6)

8

In [9]:
choice = "apple"

In [10]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [11]:
choice = "oranges"

In [12]:
if choice == "apple":

    print("You choose apples.")

elif choice == "orange":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You did not choose apples or oranges.


In [13]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You did not choose apples or oranges.
Thank you, shop again!


In [14]:
from IPython.core.display import display, HTML

In [15]:
import numpy as np
import matplotlib.pyplot as plt

In [16]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [17]:
a = np.arange(52)

In [18]:
shuffle(a)

array([ 2, 31, 39, 46, 29, 35, 14,  0, 15, 42, 23, 36, 10, 21,  9, 43,  4,
       13, 19, 22, 12, 38, 34,  5, 24, 37, 32, 51, 41, 17, 11, 33, 44, 26,
       48,  3, 16, 45, 50, 30,  1,  6,  8, 20, 28, 25, 49, 27, 18,  7, 47,
       40])

In [19]:
np.random.permutation(52)

array([42, 51, 35, 13, 45, 30, 18, 11, 46, 43, 16,  9, 34,  0, 28, 26,  3,
       49, 29, 32,  6, 40, 48,  8, 22,  4, 27, 44, 31, 17, 25,  5, 10, 39,
       33, 24,  2, 15, 38, 47, 50, 14, 23, 36, 20,  7,  1, 37, 12, 21, 41,
       19])

In [58]:
%%timeit
shuffle(a)

162 µs ± 1.21 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [21]:
%%timeit
np.random.permutation(52)

3.5 µs ± 261 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [56]:
cards = np.random.permutation(52)

In [57]:
cards[0]

25

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [27]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [60]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [59]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [30]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [31]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [32]:
cards = np.random.permutation(52)

In [33]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [62]:
top_of_deck,second_card_in_deck,last_card_in_deck

('Ten of Hearts', 'Seven of Hearts', 'Seven of Clubs')

In [35]:
for i in range(5):
    print(card_name(cards[i]))

Ten of Hearts
Seven of Hearts
Ten of Diamonds
Nine of Clubs
Three of Clubs


In [36]:
card_name(51)

'King of Diamonds'

In [37]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [38]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [39]:
from IPython.core.display import display, HTML

In [40]:
i = np.random.randint(4)
j = np.random.randint(13)

In [41]:
suit[i]

's'

In [42]:
card[j]

'8'

In [43]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [44]:
img = card_url_head + suit[i]+card[j] + card_url_tail

In [45]:
show_img(img)

In [47]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [48]:
card_image(3)

'k4'

In [49]:
img = card_url_head + card_image(3) + card_url_tail

In [50]:
show_img(img)

In [51]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)